import { Router } from "express";
import authRoutes from "./auth.routes";
import studentRoutes from "./student.routes";
import teacherRoutes from "./teacher.routes";
import classRoutes from "./class.routes";
import subjectRoutes from "./subject.routes";
import sessionRoutes from "./session.routes";
import attendanceRoutes from "./attendance.routes";
import resultRoutes from "./result.routes";
import feeRoutes from "./fee.routes";
import paymentRoutes from "./payment.routes";
import assignmentRoutes from "./assignment.routes";
import announcementRoutes from "./announcement.routes";
import settingRoutes from "./setting.routes";
import reportRoutes from "./report.routes";
import timetableRoutes from "./timetable.routes";
import reportcardRoutes from "./reportcard.routes";
import messageRoutes from "./message.routes";
import notificationRoutes from "./notification.routes";
import libraryRoutes from "./library.routes";
import admissionRoutes from "./admission.routes";
import analyticsRoutes from "./analytics.routes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/students", studentRoutes);
router.use("/teachers", teacherRoutes);
router.use("/classes", classRoutes);
router.use("/subjects", subjectRoutes);
router.use("/sessions", sessionRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/results", resultRoutes);
router.use("/fees", feeRoutes);
router.use("/payments", paymentRoutes);
router.use("/assignments", assignmentRoutes);
router.use("/announcements", announcementRoutes);
router.use("/settings", settingRoutes);
router.use("/reports", reportRoutes);
router.use("/timetable", timetableRoutes);
router.use("/report-cards", reportcardRoutes);
router.use("/messages", messageRoutes);
router.use("/notifications", notificationRoutes);
router.use("/library", libraryRoutes);
router.use("/admissions", admissionRoutes);
router.use("/analytics", analyticsRoutes);

export default router;
